const speciesMinimialData = [
    { "id": 1, "label": "Tiger", "imageUrl": "https://placehold.co/400?text=Tiger" },
    { "id": 2, "label": "Penguin", "imageUrl": "https://placehold.co/400?text=Penguin" },
    { "id": 3, "label": "Lion", "imageUrl": "https://placehold.co/400?text=Lion" },
    { "id": 4, "label": "Elephant", "imageUrl": "https://placehold.co/400?text=Elephant" },
    { "id": 5, "label": "Zebra", "imageUrl": "https://placehold.co/400?text=Zebra" },
    { "id": 6, "label": "Kangaroo", "imageUrl": "https://placehold.co/400?text=Kangaroo" },
    { "id": 7, "label": "Giraffe", "imageUrl": "https://placehold.co/400?text=Giraffe" },
    { "id": 8, "label": "Panda", "imageUrl": "https://placehold.co/400?text=Panda" },
    { "id": 9, "label": "Peacock", "imageUrl": "https://placehold.co/400?text=Peacock" },
    { "id": 10, "label": "Cheetah", "imageUrl": "https://placehold.co/400?text=Cheetah" },
    { "id": 11, "label": "Dolphin", "imageUrl": "https://placehold.co/400?text=Dolphin" },
    { "id": 12, "label": "Shark", "imageUrl": "https://placehold.co/400?text=Shark" },
    { "id": 13, "label": "Whale", "imageUrl": "https://placehold.co/400?text=Whale" },
    { "id": 14, "label": "Bear", "imageUrl": "https://placehold.co/400?text=Bear" },
    { "id": 15, "label": "Wolf", "imageUrl": "https://placehold.co/400?text=Wolf" },
    { "id": 16, "label": "Rhinoceros", "imageUrl": "https://placehold.co/400?text=Rhinoceros" },
    { "id": 17, "label": "Hippo", "imageUrl": "https://placehold.co/400?text=Hippo" },
    { "id": 18, "label": "Koala", "imageUrl": "https://placehold.co/400?text=Koala" },
    { "id": 19, "label": "Flamingo", "imageUrl": "https://placehold.co/400?text=Flamingo" },
    { "id": 20, "label": "Owl", "imageUrl": "https://placehold.co/400?text=Owl" },
    { "id": 21, "label": "Parrot", "imageUrl": "https://placehold.co/400?text=Parrot" },
    { "id": 22, "label": "Rabbit", "imageUrl": "https://placehold.co/400?text=Rabbit" },
    { "id": 23, "label": "Squirrel", "imageUrl": "https://placehold.co/400?text=Squirrel" },
    { "id": 24, "label": "Fox", "imageUrl": "https://placehold.co/400?text=Fox" },
    { "id": 25, "label": "Leopard", "imageUrl": "https://placehold.co/400?text=Leopard" },
    { "id": 26, "label": "Crocodile", "imageUrl": "https://placehold.co/400?text=Crocodile" },
    { "id": 27, "label": "Snake", "imageUrl": "https://placehold.co/400?text=Snake" },
    { "id": 28, "label": "Turtle", "imageUrl": "https://placehold.co/400?text=Turtle" },
    { "id": 29, "label": "Frog", "imageUrl": "https://placehold.co/400?text=Frog" },
    { "id": 30, "label": "Octopus", "imageUrl": "https://placehold.co/400?text=Octopus" }
];

const occurenceMinimalData=[
    { "id": 1, "label": "Tiger", "imageUrl": "https://placehold.co/400?text=Tiger" },
    { "id": 2, "label": "Penguin", "imageUrl": "https://placehold.co/400?text=Penguin" },
    { "id": 3, "label": "Lion", "imageUrl": "https://placehold.co/400?text=Lion" },
    { "id": 4, "label": "Elephant", "imageUrl": "https://placehold.co/400?text=Elephant" },
    { "id": 5, "label": "Zebra", "imageUrl": "https://placehold.co/400?text=Zebra" },
    { "id": 6, "label": "Kangaroo", "imageUrl": "https://placehold.co/400?text=Kangaroo" },
    { "id": 7, "label": "Giraffe", "imageUrl": "https://placehold.co/400?text=Giraffe" },
    { "id": 8, "label": "Panda", "imageUrl": "https://placehold.co/400?text=Panda" },
    { "id": 9, "label": "Peacock", "imageUrl": "https://placehold.co/400?text=Peacock" },
    { "id": 10, "label": "Cheetah", "imageUrl": "https://placehold.co/400?text=Cheetah" },
    { "id": 11, "label": "Dolphin", "imageUrl": "https://placehold.co/400?text=Dolphin" },
    { "id": 12, "label": "Shark", "imageUrl": "https://placehold.co/400?text=Shark" },
    { "id": 13, "label": "Whale", "imageUrl": "https://placehold.co/400?text=Whale" },
    { "id": 14, "label": "Bear", "imageUrl": "https://placehold.co/400?text=Bear" },
    { "id": 15, "label": "Wolf", "imageUrl": "https://placehold.co/400?text=Wolf" },
    { "id": 16, "label": "Rhinoceros", "imageUrl": "https://placehold.co/400?text=Rhinoceros" },
    { "id": 17, "label": "Hippo", "imageUrl": "https://placehold.co/400?text=Hippo" },
    { "id": 18, "label": "Koala", "imageUrl": "https://placehold.co/400?text=Koala" },
    { "id": 19, "label": "Flamingo", "imageUrl": "https://placehold.co/400?text=Flamingo" },
    { "id": 20, "label": "Owl", "imageUrl": "https://placehold.co/400?text=Owl" },
    { "id": 21, "label": "Parrot", "imageUrl": "https://placehold.co/400?text=Parrot" },
    { "id": 22, "label": "Rabbit", "imageUrl": "https://placehold.co/400?text=Rabbit" },
    { "id": 23, "label": "Squirrel", "imageUrl": "https://placehold.co/400?text=Squirrel" },
    { "id": 24, "label": "Fox", "imageUrl": "https://placehold.co/400?text=Fox" },
    { "id": 25, "label": "Leopard", "imageUrl": "https://placehold.co/400?text=Leopard" },
    { "id": 26, "label": "Crocodile", "imageUrl": "https://placehold.co/400?text=Crocodile" },
    { "id": 27, "label": "Snake", "imageUrl": "https://placehold.co/400?text=Snake" },
    { "id": 28, "label": "Turtle", "imageUrl": "https://placehold.co/400?text=Turtle" },
    { "id": 29, "label": "Frog", "imageUrl": "https://placehold.co/400?text=Frog" },
    { "id": 30, "label": "Octopus", "imageUrl": "https://placehold.co/400?text=Octopus" }
]


export { speciesMinimialData,occurenceMinimalData };
